#!/bin/bash

DIR="$HOME/.config/sketchybar"
ITEM_DIR="$DIR/items"
PLUGIN_DIR="$DIR/plugins"

FONT="Terminess Nerd Font"
ICON_FONT="Terminess Nerd Font"

FONT_SIZE=16
ICON_FONT_SIZE=18

PADDING=6

source "$DIR/colors.sh"
source "$DIR/icons.sh"

BAR_PROPS=(
  height=32
  color=$BG_PRI_COLR
  border_color=$PEACH
  border_width=0
  shadow=off
  position=top
  sticky=on
  padding_right=15
  padding_left=15
  corner_radius=10
  y_offset=6
  margin=6
  blur_radius=32
  notch_width=200
)

DEF_PROPS=(
  updates=when_shown
  icon.font="$ICON_FONT:Regular:$ICON_FONT_SIZE.0"
  icon.color=$WHITE
  icon.padding_left=10
  icon.padding_right=2
  label.font="$FONT:Regular:$FONT_SIZE.0"
  label.color=$WHITE
  label.padding_left=$PADDING
  label.padding_right=10
  background.color=$BG_PRI_COLOR
  background.padding_right=$PADDING
  background.padding_left=$PADDING
  background.height=22
  background.corner_radius=8
)

sketchybar --bar "${BAR_PROPS[@]}"
sketchybar --default "${DEF_PROPS[@]}"

sketchybar --add event window_focus \
           --add event title_change

# -- LEFT Side Items --
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- RIGHT Side Items -- 
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
#source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/cpu_temp.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/wifi.sh"
sketchybar --add item cat left \
\ #        --set cat icon="≽^•⩊•^≼"\
           --set cat icon="ฅ^•ﻌ•^ฅ"\
                     icon.font="$ICON_FONT:Regular:24.0" \
                     icon.color=$DARK_WHITE\
                     label.drawing=off


sketchybar --hotload on

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

